### 1) Pre-processing of the data.

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split, cross_val_score, StratifiedKFold
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, roc_curve, auc
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression

# Load & Pre-process
df = pd.read_csv("JGM.csv")
df = df.drop(columns=["team_nr", "tijd"])
df["gehaald"] = df["gehaald"].map({1: 0, 2: 1})

X = df.drop("gehaald", axis=1)
y = df["gehaald"]

# Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

### 2) Baseline model.

In [2]:
# Train
model = LogisticRegression(random_state=42)

pipe_base = Pipeline([("model", model)])
pipe_base.fit(X_train, y_train)
y_pred = pipe_base.predict(X_test)

c:\Users\Freark\miniconda3\envs\ML\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [3]:
# Eval

print("Test scores:")
print("Accuracy:", accuracy_score(y_test, y_pred))
print("precision_score:", precision_score(y_test, y_pred))
print("recall_score:", recall_score(y_test, y_pred))
print("f1_score:", f1_score(y_test, y_pred))
print("---")
print(confusion_matrix(y_test, y_pred))
print("---")
print("Cross-val scores:")

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
cv_scores = cross_val_score(pipe_base, X, y, cv=cv, scoring="f1")

print(cv_scores)
print(f"{cv_scores.mean()} - {cv_scores.std()}")

c:\Users\Freark\miniconda3\envs\ML\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\Freark\miniconda3\envs\ML\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-

Test scores:
Accuracy: 0.7457627118644068
precision_score: 0.7291666666666666
recall_score: 0.9459459459459459
f1_score: 0.8235294117647058
---
[[ 9 13]
 [ 2 35]]
---
Cross-val scores:


c:\Users\Freark\miniconda3\envs\ML\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[0.73972603 0.85333333 0.77333333 0.75       0.76056338]
0.7753912148691234 - 0.04053589218356915


c:\Users\Freark\miniconda3\envs\ML\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\Freark\miniconda3\envs\ML\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-

### 3) MinMax-Scaler model.

In [4]:
from sklearn.preprocessing import MinMaxScaler

minMaxScaler = MinMaxScaler()

# Train
pipe_minmax = Pipeline([("scaler", minMaxScaler), ("model", model)])
pipe_minmax.fit(X_train, y_train)
y_pred = pipe_minmax.predict(X_test)

In [5]:
# Eval

print("Test scores:")
print("Accuracy:", accuracy_score(y_test, y_pred))
print("precision_score:", precision_score(y_test, y_pred))
print("recall_score:", recall_score(y_test, y_pred))
print("f1_score:", f1_score(y_test, y_pred))
print("---")
print(confusion_matrix(y_test, y_pred))
print("---")
print("Cross-val scores:")

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
cv_scores = cross_val_score(pipe_minmax, X, y, cv=cv, scoring="f1")

print(cv_scores)
print(f"{cv_scores.mean()} - {cv_scores.std()}")

Test scores:
Accuracy: 0.711864406779661
precision_score: 0.7083333333333334
recall_score: 0.918918918918919
f1_score: 0.8
---
[[ 8 14]
 [ 3 34]]
---
Cross-val scores:
[0.82051282 0.82051282 0.84210526 0.78378378 0.8       ]
0.8133829375934638 - 0.019909070152050144


### 4) Standardized-Scaler model.

In [6]:
from sklearn.preprocessing import StandardScaler

stdScaler = StandardScaler()

# Train
pipe_standard = Pipeline([("scaler", stdScaler), ("model", model)])
pipe_standard.fit(X_train, y_train)
y_pred = pipe_standard.predict(X_test)

In [7]:
# Eval

print("Test scores:")
print("Accuracy:", accuracy_score(y_test, y_pred))
print("precision_score:", precision_score(y_test, y_pred))
print("recall_score:", recall_score(y_test, y_pred))
print("f1_score:", f1_score(y_test, y_pred))
print("---")
print(confusion_matrix(y_test, y_pred))
print("---")
print("Cross-val scores:")

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
cv_scores = cross_val_score(pipe_standard, X, y, cv=cv, scoring="f1")

print(cv_scores)
print(f"{cv_scores.mean()} - {cv_scores.std()}")

Test scores:
Accuracy: 0.7457627118644068
precision_score: 0.72
recall_score: 0.972972972972973
f1_score: 0.8275862068965517
---
[[ 8 14]
 [ 1 36]]
---
Cross-val scores:
[0.72222222 0.87179487 0.67567568 0.75675676 0.76712329]
0.758714562824152 - 0.0649443510038087


### 5) Standardized model - Feature Selection

In [8]:
from sklearn.feature_selection import SelectKBest, chi2

# Preprocessing
X_feature = SelectKBest(chi2).fit_transform(X, y)
X_train_feature, X_test_feature, y_train_feature, y_test_feature = train_test_split(X_feature, y, test_size=0.2, random_state=42, stratify=y)

# Train
pipe_feature = Pipeline([("scaler", stdScaler), ("model", model)])
pipe_feature.fit(X_train_feature, y_train_feature)
y_pred = pipe_feature.predict(X_test_feature)

In [9]:
# Eval

print("Test scores:")
print("Accuracy:", accuracy_score(y_test_feature, y_pred))
print("precision_score:", precision_score(y_test_feature, y_pred))
print("recall_score:", recall_score(y_test_feature, y_pred))
print("f1_score:", f1_score(y_test_feature, y_pred))
print("---")
print(confusion_matrix(y_test_feature, y_pred))
print("---")
print("Cross-val scores:")

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
cv_scores = cross_val_score(pipe_feature, X_feature, y, cv=cv, scoring="f1")

print(cv_scores)
print(f"{cv_scores.mean()} - {cv_scores.std()}")

Test scores:
Accuracy: 0.847457627118644
precision_score: 0.8333333333333334
recall_score: 0.9459459459459459
f1_score: 0.8860759493670886
---
[[15  7]
 [ 2 35]]
---
Cross-val scores:
[0.775      0.83783784 0.88       0.77333333 0.82857143]
0.8189485199485199 - 0.04046951339655217


### 6) Standardized, feature-selected, model - Hyperparameter optimalization

In [10]:
from sklearn.model_selection import GridSearchCV
import numpy as np

# Grid Search
param_grid = {
    "model__penalty": ["l2", None],
    "model__C": np.arange(0.1, 2, 0.1),
    "model__max_iter": range(25, 250, 25)
}

gridsearch = GridSearchCV(pipe_feature, param_grid, n_jobs=-1, scoring="f1", verbose=5)
gridsearch.fit(X_train_feature, y_train_feature)

print(gridsearch.best_params_)
print(gridsearch.best_score_)

best_model = gridsearch.best_estimator_

y_pred = best_model.predict(X_test_feature)

Fitting 5 folds for each of 342 candidates, totalling 1710 fits
{'model__C': np.float64(0.2), 'model__max_iter': 25, 'model__penalty': 'l2'}
0.8158960461254441


In [11]:
# Eval

print("Test scores:")
print("Accuracy:", accuracy_score(y_test_feature, y_pred))
print("precision_score:", precision_score(y_test_feature, y_pred))
print("recall_score:", recall_score(y_test_feature, y_pred))
print("f1_score:", f1_score(y_test_feature, y_pred))
print("---")
print(confusion_matrix(y_test_feature, y_pred))
print("---")
print("Cross-val scores:")

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
cv_scores = cross_val_score(best_model, X_feature, y, cv=cv, scoring="f1")

print(cv_scores)
print(f"{cv_scores.mean()} - {cv_scores.std()}")

Test scores:
Accuracy: 0.847457627118644
precision_score: 0.8333333333333334
recall_score: 0.9459459459459459
f1_score: 0.8860759493670886
---
[[15  7]
 [ 2 35]]
---
Cross-val scores:
[0.775      0.83783784 0.88       0.78947368 0.81690141]
0.8198425860998138 - 0.0371066619040764
